import { Challenge } from '@/types/carbon';

export const CHALLENGES: Challenge[] = [
  {
    id: 'meatless-monday',
    title: 'Meatless Monday',
    description: 'Skip meat every Monday. Try dal, paneer, or a veggie thali instead.',
    icon: '🥗',
    category: 'food',
    estimatedSavingsKg: 5.5,
    durationDays: 30,
  },
  {
    id: 'public-transport',
    title: 'Public Transport Day',
    description: 'Take the bus, metro, or train instead of driving on Tuesdays.',
    icon: '🚌',
    category: 'transport',
    estimatedSavingsKg: 4.2,
    durationDays: 30,
  },
  {
    id: 'zero-waste-wednesday',
    title: 'Zero Waste Wednesday',
    description: 'Produce zero non-recyclable waste. Carry your own bag and bottle.',
    icon: '♻️',
    category: 'lifestyle',
    estimatedSavingsKg: 2.0,
    durationDays: 30,
  },
  {
    id: 'no-buy-thursday',
    title: 'No-Buy Thursday',
    description: 'Avoid all non-essential purchases. Resist online shopping temptations.',
    icon: '🚫',
    category: 'lifestyle',
    estimatedSavingsKg: 3.0,
    durationDays: 30,
  },
  {
    id: 'bike-friday',
    title: 'Bike Friday',
    description: 'Cycle or walk for all trips under 5 km. Good for health and the planet.',
    icon: '🚲',
    category: 'transport',
    estimatedSavingsKg: 3.8,
    durationDays: 30,
  },
  {
    id: 'local-food-saturday',
    title: 'Local Food Saturday',
    description: 'Buy only locally sourced food from nearby markets. Reduce food miles.',
    icon: '🌾',
    category: 'food',
    estimatedSavingsKg: 2.5,
    durationDays: 30,
  },
  {
    id: 'digital-detox-sunday',
    title: 'Digital Detox Sunday',
    description: 'Limit screen time to 2 hours. Save energy from devices and data centers.',
    icon: '📵',
    category: 'energy',
    estimatedSavingsKg: 1.5,
    durationDays: 30,
  },
  {
    id: 'cold-wash-week',
    title: 'Cold Wash Week',
    description: 'Wash clothes in cold water all week. Saves electricity from water heating.',
    icon: '🧊',
    category: 'energy',
    estimatedSavingsKg: 3.2,
    durationDays: 30,
  },
  {
    id: 'plant-a-tree',
    title: 'Plant a Tree',
    description: 'Plant one tree or sapling this month. Each tree absorbs ~22 kg CO2/year.',
    icon: '🌱',
    category: 'lifestyle',
    estimatedSavingsKg: 22.0,
    durationDays: 30,
  },
  {
    id: 'ac-reduction',
    title: 'AC at 26°C',
    description: 'Set your AC to 26°C or higher. Each degree saves 3-5% energy.',
    icon: '❄️',
    category: 'energy',
    estimatedSavingsKg: 8.0,
    durationDays: 30,
  },
  {
    id: 'carpool-challenge',
    title: 'Carpool Champion',
    description: 'Share rides with colleagues or neighbors at least 3 times this week.',
    icon: '🚗',
    category: 'transport',
    estimatedSavingsKg: 6.0,
    durationDays: 30,
  },
  {
    id: 'unplug-electronics',
    title: 'Unplug & Save',
    description: 'Unplug all electronics when not in use. Phantom loads waste 5-10% energy.',
    icon: '🔌',
    category: 'energy',
    estimatedSavingsKg: 4.5,
    durationDays: 30,
  },
];

export const CHALLENGE_CATEGORY_COLORS: Record<string, string> = {
  transport: '#3B82F6',
  food: '#10B981',
  energy: '#F59E0B',
  lifestyle: '#8B5CF6',
};
